version: '2'

services:
  web:
    #build: .
    image: bovoid/geo_tm
    volumes: 
      - ./:/var/project
    ports:
      - '4242:4242'
    links:
      - db

  db:
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
